version: '3.1'

services:
  manager:
    build:
      context: .
    environment:
      - MANAGER=true
  workers:
    depends_on:
      - manager
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - UPLINK=manager:8081
