version: '3.1'

services:
  manager:
    build:
      context: .
    environment:
      - MANAGER=true
    ports:
      - 8081:8081
  workers:
    depends_on:
      - manager
    build:
      context: .
    environment:
      - UPLINK=manager:8081
