version: '3.1'

services:
  known:
    build:
      context: .
  unknown:
    depends_on:
      - known
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - UPLINK=known:8081
